site_language: en

collections:
  all_pages:
    output: true
    permalink: /:name/index.html
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

sass:
  sass_dir: _sass
  sourcemap: always
  style: compressed

markdown: CommonMarkGhPages
commonmark:
  options: ["UNSAFE"]
  extensions: []