header: |-
  **Somatisches Lernen**

  Körperarbeit - Bewegung - Tanz
footer: >-
  Kontakt: [Christian Apschner](mailto:christian.ap@gmx.net), Vorgartenstraße
  112/25, 1020 Wien, +43 650 8931081


  [Impressum / Datenschutz](/impressum)
favicon: /assets/uploads/smile.png
